// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_uHFeNam0oiTpbtP5ktNrakRdKwl1aA',
    appId: '1:557148050150:web:b57e1bb39632c59e22e127',
    messagingSenderId: '557148050150',
    projectId: 'cw6h-16575',
    authDomain: 'cw6h-16575.firebaseapp.com',
    storageBucket: 'cw6h-16575.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6b9TN2iPD8miEWGfy-GjLnO8G0prHjy0',
    appId: '1:557148050150:android:c4c4d71c11ef73ce22e127',
    messagingSenderId: '557148050150',
    projectId: 'cw6h-16575',
    storageBucket: 'cw6h-16575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwTu1969dFepkwiJjO1fs92Mpy6Ns_ZV4',
    appId: '1:557148050150:ios:4d68b601be77cbfc22e127',
    messagingSenderId: '557148050150',
    projectId: 'cw6h-16575',
    storageBucket: 'cw6h-16575.firebasestorage.app',
    iosBundleId: 'com.example.cw6h',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwTu1969dFepkwiJjO1fs92Mpy6Ns_ZV4',
    appId: '1:557148050150:ios:4d68b601be77cbfc22e127',
    messagingSenderId: '557148050150',
    projectId: 'cw6h-16575',
    storageBucket: 'cw6h-16575.firebasestorage.app',
    iosBundleId: 'com.example.cw6h',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_uHFeNam0oiTpbtP5ktNrakRdKwl1aA',
    appId: '1:557148050150:web:f4f5e67b361268d722e127',
    messagingSenderId: '557148050150',
    projectId: 'cw6h-16575',
    authDomain: 'cw6h-16575.firebaseapp.com',
    storageBucket: 'cw6h-16575.firebasestorage.app',
  );
}
